-- ═══════════════════════════════════════════════════════════
-- Red Cross Kirinyaga University — PostgreSQL & Storage Schema
-- Run this in Supabase SQL Editor to configure all tables,
-- storage buckets, row level security (RLS), and security policies.
-- ═══════════════════════════════════════════════════════════

-- ── 1. Admins Table ──
CREATE TABLE IF NOT EXISTS public.admins (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) UNIQUE NOT NULL,
  password_hash TEXT NOT NULL,
  phone VARCHAR(50),
  role VARCHAR(50) DEFAULT 'admin' CHECK (role IN ('superadmin', 'admin')),
  avatar TEXT,
  is_active BOOLEAN DEFAULT true,
  last_login TIMESTAMP WITH TIME ZONE,
  password_reset_token TEXT,
  password_reset_expires TIMESTAMP WITH TIME ZONE,
  refresh_tokens TEXT[] DEFAULT '{}',
  notification_preferences JSONB DEFAULT '{"email": true, "push": true, "approvals": true, "messages": true}'::jsonb,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc', now()),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc', now())
);

-- ── 2. Members Table ──
CREATE TABLE IF NOT EXISTS public.members (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) UNIQUE NOT NULL,
  phone VARCHAR(50),
  role VARCHAR(100) DEFAULT 'Member',
  status VARCHAR(50) DEFAULT 'active',
  joined TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc', now()),
  avatar TEXT,
  notes TEXT,
  created_by UUID REFERENCES public.admins(id) ON DELETE SET NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc', now()),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc', now())
);

-- Migration safety for existing tables:
DO $$
BEGIN
  -- Relax status check constraint if present
  IF EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'members_status_check') THEN
    ALTER TABLE public.members DROP CONSTRAINT members_status_check;
  END IF;
  ALTER TABLE public.members ADD CONSTRAINT members_status_check 
    CHECK (status IN ('active', 'inactive', 'pending', 'rejected', 'approved'));
EXCEPTION
  WHEN others THEN NULL;
END $$;


-- ── 3. Events Table ──
CREATE TABLE IF NOT EXISTS public.events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  date DATE,
  time TIME,
  location VARCHAR(255),
  description TEXT,
  image_url TEXT,
  category VARCHAR(100) DEFAULT 'General',
  submitted_by_name VARCHAR(255),
  submitted_by_email VARCHAR(255),
  status VARCHAR(50) DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'rejected')),
  submitted_by UUID,
  rejection_reason TEXT,
  approved_by UUID,
  approved_at TIMESTAMP WITH TIME ZONE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc', now()),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc', now())
);

-- Migration safety for events columns
DO $$
BEGIN
  ALTER TABLE public.events ADD COLUMN IF NOT EXISTS category VARCHAR(100) DEFAULT 'General';
  ALTER TABLE public.events ADD COLUMN IF NOT EXISTS submitted_by_name VARCHAR(255);
  ALTER TABLE public.events ADD COLUMN IF NOT EXISTS submitted_by_email VARCHAR(255);
  -- Relax submitted_by FK if it exists to allow members to submit
  IF EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'events_submitted_by_fkey') THEN
    ALTER TABLE public.events DROP CONSTRAINT events_submitted_by_fkey;
  END IF;
  IF EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'events_approved_by_fkey') THEN
    ALTER TABLE public.events DROP CONSTRAINT events_approved_by_fkey;
  END IF;
EXCEPTION
  WHEN others THEN NULL;
END $$;


-- ── 4. Gallery Table ──
CREATE TABLE IF NOT EXISTS public.gallery (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title VARCHAR(255) DEFAULT 'Untitled',
  type VARCHAR(50) DEFAULT 'image' CHECK (type IN ('image', 'video')),
  image_url TEXT NOT NULL,
  thumbnail TEXT,
  public_id VARCHAR(255),
  status VARCHAR(50) DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'rejected')),
  submitted_by UUID REFERENCES public.admins(id) ON DELETE SET NULL,
  approved_by UUID REFERENCES public.admins(id) ON DELETE SET NULL,
  rejection_reason TEXT,
  tags TEXT[] DEFAULT '{}',
  likes INTEGER DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc', now()),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc', now())
);

-- ── 5. First Aid Resources Table ──
CREATE TABLE IF NOT EXISTS public.first_aid (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  content TEXT,
  video_url TEXT,
  image_url TEXT,
  category VARCHAR(100),
  sort_order INTEGER DEFAULT 0,
  created_by UUID REFERENCES public.admins(id) ON DELETE SET NULL,
  is_published BOOLEAN DEFAULT true,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc', now()),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc', now())
);

-- ── 6. Messages Table ──
CREATE TABLE IF NOT EXISTS public.messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sender_id UUID REFERENCES public.admins(id) ON DELETE SET NULL,
  sender_name VARCHAR(255),
  receiver_id UUID REFERENCES public.admins(id) ON DELETE SET NULL,
  subject VARCHAR(255),
  text TEXT NOT NULL,
  is_broadcast BOOLEAN DEFAULT false,
  is_read BOOLEAN DEFAULT false,
  read_at TIMESTAMP WITH TIME ZONE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc', now())
);

-- ── 7. Questions Table ──
CREATE TABLE IF NOT EXISTS public.questions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  question TEXT NOT NULL,
  asked_by VARCHAR(255) DEFAULT 'Anonymous',
  answer TEXT,
  answered_by UUID REFERENCES public.admins(id) ON DELETE SET NULL,
  answered_at TIMESTAMP WITH TIME ZONE,
  status VARCHAR(50) DEFAULT 'unanswered' CHECK (status IN ('unanswered', 'answered')),
  is_public BOOLEAN DEFAULT true,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc', now()),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc', now())
);

-- ── 8. Notifications Table ──
CREATE TABLE IF NOT EXISTS public.notifications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  recipient_id UUID REFERENCES public.admins(id) ON DELETE CASCADE,
  type VARCHAR(50) DEFAULT 'system' CHECK (type IN ('event', 'gallery', 'question', 'message', 'system')),
  text TEXT NOT NULL,
  link VARCHAR(255),
  is_read BOOLEAN DEFAULT false,
  read_at TIMESTAMP WITH TIME ZONE,
  meta JSONB DEFAULT '{}'::jsonb,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc', now())
);

-- ── 9. Leaders Table ──
CREATE TABLE IF NOT EXISTS public.leaders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  role VARCHAR(255) NOT NULL,
  image TEXT,
  bio TEXT,
  email VARCHAR(255),
  phone VARCHAR(50),
  sort_order INTEGER DEFAULT 0,
  status VARCHAR(50) DEFAULT 'active' CHECK (status IN ('active', 'inactive')),
  created_by UUID REFERENCES public.admins(id) ON DELETE SET NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc', now()),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc', now())
);

-- ── 10. Hero Slides Table (Frontend Homepage Banners) ──
CREATE TABLE IF NOT EXISTS public.hero_slides (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  eyebrow VARCHAR(255) NOT NULL DEFAULT 'KIRINYAGA UNIVERSITY · RED CROSS CHAPTER',
  first VARCHAR(255) NOT NULL,
  accent VARCHAR(255) NOT NULL,
  description TEXT NOT NULL,
  primary_button_text VARCHAR(100) DEFAULT 'Learn About Us',
  primary_href VARCHAR(255) DEFAULT '/about',
  secondary_button_text VARCHAR(100) DEFAULT 'Join the Chapter',
  secondary_href VARCHAR(255) DEFAULT '/contact',
  image TEXT NOT NULL,
  sort_order INTEGER DEFAULT 1,
  status VARCHAR(50) DEFAULT 'active' CHECK (status IN ('active', 'inactive')),
  created_by UUID REFERENCES public.admins(id) ON DELETE SET NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc', now()),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc', now())
);

-- ═══════════════════════════════════════════════════════════
-- INDEXES for optimal query performance
-- ═══════════════════════════════════════════════════════════
CREATE INDEX IF NOT EXISTS idx_admins_email ON public.admins(email);
CREATE INDEX IF NOT EXISTS idx_members_email ON public.members(email);
CREATE INDEX IF NOT EXISTS idx_members_status ON public.members(status);
CREATE INDEX IF NOT EXISTS idx_events_status ON public.events(status);
CREATE INDEX IF NOT EXISTS idx_events_date ON public.events(date);
CREATE INDEX IF NOT EXISTS idx_gallery_status ON public.gallery(status);
CREATE INDEX IF NOT EXISTS idx_questions_status ON public.questions(status);
CREATE INDEX IF NOT EXISTS idx_notifications_recipient ON public.notifications(recipient_id);
CREATE INDEX IF NOT EXISTS idx_notifications_unread ON public.notifications(recipient_id, is_read);
CREATE INDEX IF NOT EXISTS idx_leaders_status ON public.leaders(status);
CREATE INDEX IF NOT EXISTS idx_leaders_sort_order ON public.leaders(sort_order);
CREATE INDEX IF NOT EXISTS idx_hero_slides_status ON public.hero_slides(status);
CREATE INDEX IF NOT EXISTS idx_hero_slides_sort_order ON public.hero_slides(sort_order);


-- ═══════════════════════════════════════════════════════════
-- SUPABASE STORAGE BUCKET CONFIGURATION
-- Buckets: 'Store' and 'redcross-media'
-- ═══════════════════════════════════════════════════════════

-- Ensure the storage buckets exist
INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES 
  (
    'Store',
    'Store',
    true,
    20971520, -- 20 MB
    ARRAY[
      'image/jpeg', 'image/png', 'image/gif', 'image/webp', 'image/svg+xml',
      'video/mp4', 'video/webm', 'video/quicktime', 'video/x-msvideo',
      'application/pdf', 'application/msword',
      'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
      'application/vnd.ms-excel',
      'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
      'text/plain', 'text/csv'
    ]
  ),
  (
    'redcross-media',
    'redcross-media',
    true,
    20971520, -- 20 MB
    ARRAY[
      'image/jpeg', 'image/png', 'image/gif', 'image/webp', 'image/svg+xml',
      'video/mp4', 'video/webm', 'video/quicktime', 'video/x-msvideo',
      'application/pdf', 'application/msword',
      'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
      'application/vnd.ms-excel',
      'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
      'text/plain', 'text/csv'
    ]
  )
ON CONFLICT (id) DO UPDATE SET
  public = true,
  file_size_limit = 20971520,
  allowed_mime_types = EXCLUDED.allowed_mime_types;

-- ═══════════════════════════════════════════════════════════
-- STORAGE ROW LEVEL SECURITY & POLICIES (Handled safely)
-- ═══════════════════════════════════════════════════════════
DO $$
BEGIN
  -- Storage policies
  BEGIN
    DROP POLICY IF EXISTS "Public Read Access for Media Buckets" ON storage.objects;
    CREATE POLICY "Public Read Access for Media Buckets"
    ON storage.objects FOR SELECT
    USING (bucket_id IN ('Store', 'redcross-media'));
  EXCEPTION WHEN others THEN NULL;
  END;

  BEGIN
    DROP POLICY IF EXISTS "Allow Upload to Media Buckets" ON storage.objects;
    CREATE POLICY "Allow Upload to Media Buckets"
    ON storage.objects FOR INSERT
    WITH CHECK (bucket_id IN ('Store', 'redcross-media'));
  EXCEPTION WHEN others THEN NULL;
  END;

  BEGIN
    DROP POLICY IF EXISTS "Allow Update in Media Buckets" ON storage.objects;
    CREATE POLICY "Allow Update in Media Buckets"
    ON storage.objects FOR UPDATE
    USING (bucket_id IN ('Store', 'redcross-media'))
    WITH CHECK (bucket_id IN ('Store', 'redcross-media'));
  EXCEPTION WHEN others THEN NULL;
  END;

  BEGIN
    DROP POLICY IF EXISTS "Allow Delete from Media Buckets" ON storage.objects;
    CREATE POLICY "Allow Delete from Media Buckets"
    ON storage.objects FOR DELETE
    USING (bucket_id IN ('Store', 'redcross-media'));
  EXCEPTION WHEN others THEN NULL;
  END;
END $$;

-- ═══════════════════════════════════════════════════════════
-- DATABASE TABLES ROW LEVEL SECURITY (RLS) & POLICIES
-- ═══════════════════════════════════════════════════════════

-- ── 1. Admins Table RLS ──
ALTER TABLE public.admins ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Admins select policy" ON public.admins;
CREATE POLICY "Admins select policy" ON public.admins
  FOR SELECT USING (true);

DROP POLICY IF EXISTS "Admins insert policy" ON public.admins;
CREATE POLICY "Admins insert policy" ON public.admins
  FOR INSERT WITH CHECK (true);

DROP POLICY IF EXISTS "Admins update policy" ON public.admins;
CREATE POLICY "Admins update policy" ON public.admins
  FOR UPDATE USING (true);

DROP POLICY IF EXISTS "Admins delete policy" ON public.admins;
CREATE POLICY "Admins delete policy" ON public.admins
  FOR DELETE USING (true);

-- ── 2. Members Table RLS ──
ALTER TABLE public.members ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Members select policy" ON public.members;
CREATE POLICY "Members select policy" ON public.members
  FOR SELECT USING (true);

DROP POLICY IF EXISTS "Members insert policy" ON public.members;
CREATE POLICY "Members insert policy" ON public.members
  FOR INSERT WITH CHECK (true);

DROP POLICY IF EXISTS "Members update policy" ON public.members;
CREATE POLICY "Members update policy" ON public.members
  FOR UPDATE USING (true);

DROP POLICY IF EXISTS "Members delete policy" ON public.members;
CREATE POLICY "Members delete policy" ON public.members
  FOR DELETE USING (true);

-- ── 3. Events Table RLS ──
ALTER TABLE public.events ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Events select policy" ON public.events;
CREATE POLICY "Events select policy" ON public.events
  FOR SELECT USING (true);

DROP POLICY IF EXISTS "Events insert policy" ON public.events;
CREATE POLICY "Events insert policy" ON public.events
  FOR INSERT WITH CHECK (true);

DROP POLICY IF EXISTS "Events update policy" ON public.events;
CREATE POLICY "Events update policy" ON public.events
  FOR UPDATE USING (true);

DROP POLICY IF EXISTS "Events delete policy" ON public.events;
CREATE POLICY "Events delete policy" ON public.events
  FOR DELETE USING (true);

-- ── 4. Gallery Table RLS ──
ALTER TABLE public.gallery ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Gallery select policy" ON public.gallery;
CREATE POLICY "Gallery select policy" ON public.gallery
  FOR SELECT USING (true);

DROP POLICY IF EXISTS "Gallery insert policy" ON public.gallery;
CREATE POLICY "Gallery insert policy" ON public.gallery
  FOR INSERT WITH CHECK (true);

DROP POLICY IF EXISTS "Gallery update policy" ON public.gallery;
CREATE POLICY "Gallery update policy" ON public.gallery
  FOR UPDATE USING (true);

DROP POLICY IF EXISTS "Gallery delete policy" ON public.gallery;
CREATE POLICY "Gallery delete policy" ON public.gallery
  FOR DELETE USING (true);

-- ── 5. First Aid Table RLS ──
ALTER TABLE public.first_aid ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "First aid select policy" ON public.first_aid;
CREATE POLICY "First aid select policy" ON public.first_aid
  FOR SELECT USING (true);

DROP POLICY IF EXISTS "First aid insert policy" ON public.first_aid;
CREATE POLICY "First aid insert policy" ON public.first_aid
  FOR INSERT WITH CHECK (true);

DROP POLICY IF EXISTS "First aid update policy" ON public.first_aid;
CREATE POLICY "First aid update policy" ON public.first_aid
  FOR UPDATE USING (true);

DROP POLICY IF EXISTS "First aid delete policy" ON public.first_aid;
CREATE POLICY "First aid delete policy" ON public.first_aid
  FOR DELETE USING (true);

-- ── 6. Messages Table RLS ──
ALTER TABLE public.messages ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Messages select policy" ON public.messages;
CREATE POLICY "Messages select policy" ON public.messages
  FOR SELECT USING (true);

DROP POLICY IF EXISTS "Messages insert policy" ON public.messages;
CREATE POLICY "Messages insert policy" ON public.messages
  FOR INSERT WITH CHECK (true);

DROP POLICY IF EXISTS "Messages update policy" ON public.messages;
CREATE POLICY "Messages update policy" ON public.messages
  FOR UPDATE USING (true);

DROP POLICY IF EXISTS "Messages delete policy" ON public.messages;
CREATE POLICY "Messages delete policy" ON public.messages
  FOR DELETE USING (true);

-- ── 7. Questions Table RLS ──
ALTER TABLE public.questions ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Questions select policy" ON public.questions;
CREATE POLICY "Questions select policy" ON public.questions
  FOR SELECT USING (true);

DROP POLICY IF EXISTS "Questions insert policy" ON public.questions;
CREATE POLICY "Questions insert policy" ON public.questions
  FOR INSERT WITH CHECK (true);

DROP POLICY IF EXISTS "Questions update policy" ON public.questions;
CREATE POLICY "Questions update policy" ON public.questions
  FOR UPDATE USING (true);

DROP POLICY IF EXISTS "Questions delete policy" ON public.questions;
CREATE POLICY "Questions delete policy" ON public.questions
  FOR DELETE USING (true);

-- ── 8. Notifications Table RLS ──
ALTER TABLE public.notifications ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Notifications select policy" ON public.notifications;
CREATE POLICY "Notifications select policy" ON public.notifications
  FOR SELECT USING (true);

DROP POLICY IF EXISTS "Notifications insert policy" ON public.notifications;
CREATE POLICY "Notifications insert policy" ON public.notifications
  FOR INSERT WITH CHECK (true);

DROP POLICY IF EXISTS "Notifications update policy" ON public.notifications;
CREATE POLICY "Notifications update policy" ON public.notifications
  FOR UPDATE USING (true);

DROP POLICY IF EXISTS "Notifications delete policy" ON public.notifications;
CREATE POLICY "Notifications delete policy" ON public.notifications
  FOR DELETE USING (true);

-- ── 9. Leaders Table RLS ──
ALTER TABLE public.leaders ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Leaders select policy" ON public.leaders;
CREATE POLICY "Leaders select policy" ON public.leaders
  FOR SELECT USING (true);

DROP POLICY IF EXISTS "Leaders insert policy" ON public.leaders;
CREATE POLICY "Leaders insert policy" ON public.leaders
  FOR INSERT WITH CHECK (true);

DROP POLICY IF EXISTS "Leaders update policy" ON public.leaders;
CREATE POLICY "Leaders update policy" ON public.leaders
  FOR UPDATE USING (true);

DROP POLICY IF EXISTS "Leaders delete policy" ON public.leaders;
CREATE POLICY "Leaders delete policy" ON public.leaders
  FOR DELETE USING (true);

-- ── 10. Optional Initial Seed for Leaders ──
INSERT INTO public.leaders (name, role, image, sort_order, status)
VALUES
  ('Dennis Kiptanui', 'Chairperson', 'Dennis.jpeg', 1, 'active'),
  ('Ian Kamau', 'Vice Chairperson', 'Ian.jpeg', 2, 'active'),
  ('Mary Kahora', 'Secretary', 'Mary1.jpeg', 3, 'active'),
  ('Tabitha Cherotich', 'Treasurer', 'Tabitha.jpeg', 4, 'active'),
  ('Kennedy Macharia', 'First Aid Officer', 'ken2.jpeg', 5, 'active'),
  ('Francis Lobun', 'Asst. First Aid Officer', 'Portfolio%20.jpg', 6, 'active'),
  ('Amos Maliro', 'Organising Secretary', 'Amos.jpeg', 7, 'active'),
  ('Holinda Kiarie', 'Dissemination Officer', 'Holinda.jpeg', 8, 'active'),
  ('Orange', 'IT Personnel', 'Orange.jpeg', 9, 'active')
ON CONFLICT DO NOTHING;

