import pg from 'pg';
import dotenv from 'dotenv';
dotenv.config();

const { Client } = pg;

async function checkAndMigrate() {
  const client = new Client({
    connectionString: process.env.DATABASE_URL || 'postgresql://postgres.yqvzoenlihgutjwujecq:Learn2026more.@aws-0-eu-west-1.pooler.supabase.com:5432/postgres',
    ssl: { rejectUnauthorized: false }
  });

  try {
    await client.connect();
    console.log('Connected to PostgreSQL successfully!');

    // 1. Add missing columns to members table
    await client.query(`
      ALTER TABLE public.members ADD COLUMN IF NOT EXISTS password_hash TEXT;
      ALTER TABLE public.members ADD COLUMN IF NOT EXISTS password_reset_token TEXT;
      ALTER TABLE public.members ADD COLUMN IF NOT EXISTS password_reset_expires TIMESTAMP WITH TIME ZONE;
      ALTER TABLE public.members ADD COLUMN IF NOT EXISTS refresh_tokens TEXT[] DEFAULT '{}';
      ALTER TABLE public.members ADD COLUMN IF NOT EXISTS notification_preferences JSONB DEFAULT '{"email": true, "push": true, "messages": true}'::jsonb;
      ALTER TABLE public.members ADD COLUMN IF NOT EXISTS is_active BOOLEAN DEFAULT true;
      ALTER TABLE public.members ADD COLUMN IF NOT EXISTS last_login TIMESTAMP WITH TIME ZONE;
      ALTER TABLE public.members ADD COLUMN IF NOT EXISTS gender VARCHAR(50) DEFAULT 'Not specified';
      ALTER TABLE public.members ADD COLUMN IF NOT EXISTS date_of_birth DATE;
    `);
    console.log('✅ members table updated with password & security fields!');

    // 2. Create dissemination table
    await client.query(`
      CREATE TABLE IF NOT EXISTS public.dissemination (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        title VARCHAR(255) NOT NULL,
        category VARCHAR(100) DEFAULT 'Fundamental Principles',
        description TEXT,
        content TEXT,
        document_url TEXT,
        video_url TEXT,
        image_url TEXT,
        sort_order INTEGER DEFAULT 0,
        is_published BOOLEAN DEFAULT true,
        tags TEXT[] DEFAULT '{}',
        created_by UUID,
        created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc', now()),
        updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc', now())
      );

      CREATE INDEX IF NOT EXISTS idx_dissemination_category ON public.dissemination(category);
      CREATE INDEX IF NOT EXISTS idx_dissemination_published ON public.dissemination(is_published);
      CREATE INDEX IF NOT EXISTS idx_dissemination_sort ON public.dissemination(sort_order);

      ALTER TABLE public.dissemination ENABLE ROW LEVEL SECURITY;

      DROP POLICY IF EXISTS "Dissemination select policy" ON public.dissemination;
      CREATE POLICY "Dissemination select policy" ON public.dissemination FOR SELECT USING (true);

      DROP POLICY IF EXISTS "Dissemination insert policy" ON public.dissemination;
      CREATE POLICY "Dissemination insert policy" ON public.dissemination FOR INSERT WITH CHECK (true);

      DROP POLICY IF EXISTS "Dissemination update policy" ON public.dissemination;
      CREATE POLICY "Dissemination update policy" ON public.dissemination FOR UPDATE USING (true);

      DROP POLICY IF EXISTS "Dissemination delete policy" ON public.dissemination;
      CREATE POLICY "Dissemination delete policy" ON public.dissemination FOR DELETE USING (true);
    `);
    console.log('✅ dissemination table and policies created successfully!');

    // 3. Seed initial dissemination items if empty
    const countRes = await client.query(`SELECT count(*) FROM public.dissemination;`);
    if (parseInt(countRes.rows[0].count, 10) === 0) {
      await client.query(`
        INSERT INTO public.dissemination (title, category, description, content, image_url, sort_order, is_published, tags)
        VALUES
        (
          'The Seven Fundamental Principles of the Red Cross',
          'Fundamental Principles',
          'An in-depth guide to Humanity, Impartiality, Neutrality, Independence, Voluntary Service, Unity, and Universality.',
          'The Fundamental Principles are the bedrock of the International Red Cross and Red Crescent Movement. Proclaimed in Vienna in 1965, they bond the National Societies, the ICRC, and the IFRC together.\n\n1. Humanity: Born of a desire to bring assistance without discrimination to the wounded on the battlefield.\n2. Impartiality: Making no discrimination as to nationality, race, religious beliefs, class or political opinions.\n3. Neutrality: In order to continue to enjoy the confidence of all, the Movement may not take sides in hostilities.\n4. Independence: The Movement is independent. The National Societies must maintain their autonomy.\n5. Voluntary Service: A voluntary relief movement not prompted in any manner by desire for gain.\n6. Unity: There can be only one Red Cross or one Red Crescent Society in any one country.\n7. Universality: The International Red Cross and Red Crescent Movement, in which all Societies have equal status.',
          'https://images.unsplash.com/photo-1576765608535-5f04d1e3f289?auto=format&fit=crop&w=1200&q=80',
          1,
          true,
          ARRAY['Principles', 'Humanity', 'Core Values']
        ),
        (
          'History of the Red Cross Movement & Henri Dunant',
          'Emblem & Heritage',
          'Discover how the Battle of Solferino in 1859 inspired the birth of the world largest humanitarian movement.',
          'In June 1859, Swiss businessman Henri Dunant witnessed the horrific aftermath of the Battle of Solferino in northern Italy, where over 40,000 soldiers lay dead or wounded with virtually no medical care. Dunant mobilized local villagers to care for the wounded regardless of their allegiance, echoing the phrase "Tutti fratelli" (We are all brothers).\n\nUpon returning to Geneva, Dunant published "A Memory of Solferino" (1862), proposing voluntary national relief societies and an international treaty to protect the wounded. In 1863, the International Committee of the Red Cross was formed.',
          'https://images.unsplash.com/photo-1469571486292-0ba58a3f068b?auto=format&fit=crop&w=1200&q=80',
          2,
          true,
          ARRAY['History', 'Henri Dunant', 'Origins']
        ),
        (
          'International Humanitarian Law (IHL) & Geneva Conventions',
          'International Humanitarian Law',
          'Understanding the legal framework that limits the effects of armed conflict for humanitarian reasons.',
          'International Humanitarian Law (IHL), also known as the Law of Armed Conflict, is a set of international rules established by the Geneva Conventions and Hague Conventions.\n\nKey pillars of IHL include:\n- Protection of non-combatants (civilians, medical staff, aid workers).\n- Protection of wounded, sick, and shipwrecked armed forces.\n- Humane treatment of prisoners of war (POWs).\n- Strict limitations on weapons and warfare methods causing unnecessary suffering.',
          'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?auto=format&fit=crop&w=1200&q=80',
          3,
          true,
          ARRAY['IHL', 'Geneva Conventions', 'Humanitarian Law']
        ),
        (
          'The Red Cross Emblem: Usage, Rules & Protective Value',
          'Emblem & Heritage',
          'Guidelines on the protective and indicative use of the Red Cross emblem under international law.',
          'The Red Cross emblem—a red cross on a white ground, the reverse of the Swiss flag—is a recognized symbol of neutral humanitarian assistance and protection during armed conflict.\n\nThere are two primary uses:\n1. Protective Use: Used in wartime to identify medical personnel, facilities, and transports. Any attack against anyone bearing the protective emblem is a war crime.\n2. Indicative Use: Shows that a person or object is linked to the Red Cross Society.',
          'https://images.unsplash.com/photo-1584515979956-d9f6e5d09982?auto=format&fit=crop&w=1200&q=80',
          4,
          true,
          ARRAY['Emblem', 'Rules', 'Identity']
        ),
        (
          'Community First Aid & Chapter Volunteer Guidelines',
          'Youth & Community',
          'Standard operating procedures for KyU Red Cross Chapter volunteers during campus emergencies and outreach.',
          'As a volunteer of the Kirinyaga University Red Cross Chapter, you represent the highest standards of volunteer service and compassion.\n\nKey Volunteer Responsibilities:\n- Respond promptly and safely to emergencies on campus.\n- Maintain confidentiality of casualty records and patient dignity.\n- Participate actively in community blood drives, hygiene outreach, and disaster drills.\n- Uphold the Red Cross Code of Conduct at all times.',
          'https://images.unsplash.com/photo-1516574187841-cb9cc2ca948b?auto=format&fit=crop&w=1200&q=80',
          5,
          true,
          ARRAY['First Aid', 'Volunteering', 'Chapter Guidelines']
        );
      `);
      console.log('✅ Initial Dissemination modules seeded!');
    }

    // 4. Verify updated columns
    const cols = await client.query(`
      SELECT column_name, data_type, is_nullable 
      FROM information_schema.columns 
      WHERE table_name = 'members'
      ORDER BY ordinal_position;
    `);
    console.log('\nFinal members columns:', cols.rows.map(r => r.column_name));

  } catch (err) {
    console.error('Migration error:', err);
  } finally {
    await client.end();
  }
}

checkAndMigrate();
